// Builds (learning experiments). Edit here; the Builds cards and detail pages are rendered from this list.
// `illustrative: true` marks a designed cover rather than a screenshot of the build itself.
window.BUILDS = [
  {
    id: 'debtor-intelligence',
    title: 'Debtor Intelligence',
    kicker: 'Credit risk · Receivables analytics',
    cover: 'debtor-intelligence.jpg',
    url: 'https://claude.ai/artifact/92HdLmDx9ttGtM49uVNnLT',
    cta: 'Open the app',
    tools: ['AI-assisted build', 'Credit scoring', 'Tally / ERP exports', 'Receivables'],
    summary: 'Bank-style credit thinking applied to a business\'s own debtors ledger: it rebuilds payment history from a Tally-style export, estimates each customer\'s chance of default, and suggests credit limits.',
    overview: 'Banks score borrowers before lending, but most small businesses extend credit to customers with no scoring at all. Debtor Intelligence takes a ledger export, rebuilds bill-by-bill payment history, and turns it into a receivables risk desk: who is likely to pay, who is not, and what to do about it. It runs on a fictional demo ledger, or on your own file entirely in the browser.',
    stats: [['77', 'demo customers scored'], ['8', 'scorecard factors'], ['13 wk', 'collection forecast'], ['CR1–CR8', 'credit rating grades']],
    steps: [
      ['Import', 'Reads Tally Prime / ERP 9, Busy, Marg, Zoho Books, SAP (FBL5N) exports or any invoice list.'],
      ['Rebuild bills', 'Reconstructs each bill and its settlements from the ledger vouchers.'],
      ['Measure behaviour', 'Days early or late, depth of delays, trend, consistency, cheque returns.'],
      ['Score and test', 'Behavioural scorecard blended with a predictive model, then validated out of time.'],
      ['Adjust and act', 'Credit limits, stress tests, collection priorities and printable credit memos.'],
    ],
    features: [
      'Overview dashboard: outstanding, overdue, over-90-day balances, DSO, expected credit loss and collection efficiency',
      'Debtors table with a credit grade per customer and a drill-down showing what drives each score',
      'Behavioural scorecard: payment timeliness, depth of delays, current overdue exposure, recent trend, consistency, history depth, cheque returns and credit limit use',
      'Model validation with an out-of-time test and calibration check',
      'Insights: roll rates and cure rates, vintage analysis, customer concentration (HHI) and a 13-week collection forecast',
      'DSO target planner showing the cash released and interest saved by collecting faster',
      'Scenario planning, a new-debtor assessment form and printable credit memos',
    ],
    learned: ['Credit risk scoring and grading', 'Receivables and working capital', 'Model validation', 'Provisioning thinking (expected credit loss)'],
    note: 'Runs on fictional, synthetic demo data. All names, figures and accuracy results in the demo are illustrative.',
  },
  {
    id: 'gstr-2b-reconciliation',
    title: 'GSTR-2B Reconciliation',
    kicker: 'Indirect tax · Automation',
    cover: 'gstr-2b-reconciliation.jpg',
    url: 'https://claude.ai/artifact/HuntnsQtsKm5348iVmmvuo',
    cta: 'Open the tool',
    tools: ['AI-assisted build', 'GST', 'Excel import / export', 'ITC'],
    summary: 'Matches the purchase register against GSTR-2B and flags mismatched or missing input tax credit, then works out the ITC you can claim in GSTR-3B.',
    overview: 'Monthly GSTR-2B reconciliation is usually a manual VLOOKUP exercise. This tool takes the GSTR-2B Excel from the GST portal and a purchase register export, matches every invoice, explains every rupee of difference, and produces the lists the team actually needs: what to ask suppliers and what to fix in the books.',
    stats: [['9', 'match statuses'], ['₹10', 'default rounding tolerance'], ['3B', 'head-wise ITC output'], ['0', 'files uploaded to a server']],
    steps: [
      ['Upload', 'GSTR-2B Excel (B2B and B2B-CDNR sheets read automatically) and the purchase register from Tally or an ERP.'],
      ['Match', 'Invoices are paired on supplier GSTIN and invoice number.'],
      ['Check', 'Taxable value, tax head, date and eligibility are compared within a rupee tolerance.'],
      ['Classify', 'Each invoice gets one of nine statuses, from exact match to not in GSTR-2B.'],
      ['Report', 'Reconciliation statement, ITC for GSTR-3B, action lists and an Excel download.'],
    ],
    features: [
      'Nine statuses: matched, rounding, details differ, amount mismatch, wrong tax head, not in books, not in GSTR-2B, duplicate in books, and RCM on unregistered suppliers',
      'Reconciliation statement that starts from ITC in the books and bridges every rupee to ITC in GSTR-2B',
      'Head-wise claimable ITC for GSTR-3B, applying Sec 16(2)(aa) and blocked credit under Sec 17(5)',
      '"Ask suppliers" list for issues only the supplier can fix in GSTR-1',
      '"Correct in books" list of entries to add, fix or reverse',
      'Credit and debit notes matched separately',
      'Downloadable Excel report; files are read in the browser and never leave the page',
    ],
    learned: ['GST input tax credit rules', 'Reconciliation logic and exception handling', 'Turning a compliance task into a repeatable tool'],
    note: 'Includes sample GSTR-2B and purchase register files so it can be tried without real data. Always review before filing GSTR-3B.',
  },
  {
    id: 'finsta-quickloans',
    title: 'Finsta QuickLoans',
    kicker: 'Machine learning · Credit risk',
    cover: 'finsta-quickloans.jpg',
    illustrative: true,
    url: 'https://huggingface.co/spaces/harsha-finance/FiQL',
    cta: 'Open on Hugging Face',
    tools: ['Python', 'Machine learning', 'Hugging Face Spaces'],
    summary: 'A machine-learning credit risk idea: estimate default risk from applicant data, then auto-price an indicative interest rate and repayment schedule.',
    overview: 'Lenders price loans from risk. QuickLoans explores that idea end to end in a small app: an applicant\'s details go in, a model estimates the chance of default, and the risk translates into an indicative interest rate and a repayment schedule. It is a learning experiment, not a lending product.',
    stats: [['PD', 'default risk estimate'], ['Risk-based', 'indicative pricing'], ['EMI', 'repayment schedule']],
    steps: [
      ['Applicant data', 'The user enters the applicant\'s details.'],
      ['Estimate risk', 'A machine-learning model estimates the probability of default.'],
      ['Price the loan', 'The risk level sets an indicative interest rate.'],
      ['Schedule', 'An indicative repayment schedule is generated for the loan.'],
    ],
    features: [
      'Default-risk estimate from applicant data',
      'Risk-based indicative interest rate',
      'Indicative repayment schedule',
      'Hosted as a Hugging Face Space so it can be opened in a browser',
    ],
    learned: ['Machine-learning basics applied to credit', 'Linking risk to pricing', 'Deploying a small Python app'],
    note: 'A learning experiment exploring the idea. Outputs are indicative only.',
  },
  {
    id: 'deep-equity-research',
    title: 'Deep Equity Research',
    kicker: 'Custom GPT · Equity research',
    cover: 'deep-equity-research.jpg',
    illustrative: true,
    url: 'https://chatgpt.com/g/g-6a9c3a3b478c8191bb7454360b02e5be-deep-equity-research',
    cta: 'Open in ChatGPT',
    tools: ['ChatGPT custom GPT', 'Prompt design', 'Equity research'],
    summary: 'A custom GPT that tests how structured equity research prompts could pull company data into an analyst-style workflow.',
    overview: 'Equity research follows a familiar structure: business, industry, financials, valuation, risks and a view. This custom GPT encodes that structure in its instructions so a question about a company is answered as an analyst-style note rather than a loose chat reply.',
    stats: [['Custom GPT', 'built in ChatGPT'], ['Analyst-style', 'structured output']],
    steps: [
      ['Ask', 'Name a company or a research question.'],
      ['Gather', 'Structured prompts pull in company information.'],
      ['Structure', 'The answer follows an analyst-style research workflow.'],
    ],
    features: [
      'Structured research prompts built into the GPT\'s instructions',
      'Analyst-style workflow instead of free-form chat',
      'Opens directly in ChatGPT',
    ],
    learned: ['Prompt design for structured outputs', 'How equity research is organised', 'Where AI helps, and where it needs checking'],
    note: 'A prompt-design experiment. Research outputs should be verified against primary sources. Opening it needs a ChatGPT account.',
  },
  {
    id: 'dostpay',
    title: 'DostPay (EquiSplit)',
    kicker: 'Weekend build · Expense splitting',
    cover: 'dostpay.jpg',
    illustrative: true,
    url: 'https://dostpay.ai.studio/',
    cta: 'Open the app',
    tools: ['Google AI Studio', 'Netting logic', 'Multi-currency'],
    summary: 'A weekend build on Google AI Studio for splitting group expenses: bill-by-bill netting, multi-currency handling and debt simplification.',
    overview: 'Splitting shared costs is a small accounting problem: record who paid what, net everyone\'s position, then settle in as few payments as possible. DostPay works through that logic, including bills in different currencies.',
    stats: [['Bill-by-bill', 'netting'], ['Multi', 'currency'], ['Fewest', 'settlement payments']],
    steps: [
      ['Record bills', 'Add each bill, who paid it and who shares it.'],
      ['Net positions', 'Balances are netted bill by bill across the group.'],
      ['Convert', 'Bills in different currencies are handled.'],
      ['Simplify', 'Debts are simplified into the fewest payments to settle up.'],
    ],
    features: [
      'Bill-by-bill netting of who owes whom',
      'Multi-currency bills',
      'Debt simplification into the fewest settlement payments',
      'Built and hosted on Google AI Studio',
    ],
    learned: ['Low-code / no-code app building', 'Netting and settlement logic', 'Designing for everyday users'],
    note: 'A weekend experiment built with low-code tools.',
  },
];
